name: ustriage
summary: Output Ubuntu Server Launchpad bugs for triage
description: |
  Connect to Launchpad and collect Ubuntu Server bugs for triage.
  List can be set to a specific or range of dates and allows for
  filtering based on various options.

version: git
version-script: git rev-parse --short HEAD
grade: stable
confinement: strict
environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8

apps:
    ustriage:
        command: bin/ustriage
        plugs:
            - desktop
            - network
            - network-bind
            - home

parts:
    ustriage:
        plugin: python
        source: https://github.com/canonical/ubuntu-server-triage
        source-type: git
        stage-packages:
            - python3-dateutil
            - python3-launchpadlib
